# プロファイル保存先（chromium内推奨）
profile_dir = "chromium/profile"

# Chromium実行ファイルパス
chromium_path = "chromium/chrome.exe"

# 検索結果保存先ディレクトリ
result_dir = "result"

# 巡回する最大ページ数
max_pages = 10

# 「次へ」が連続で見つからない場合の閾値（この回数で一時停止）
max_consecutive_no_next = 2

# 検索クエリ一覧
search_queries = [
  "水素",
  "ヘリウム",
  "リチウム",
  "ベリリウム",
  "ホウ素",
  "炭素",
  "窒素",
  "酸素",
  "フッ素",
  "ネオン",
  "ナトリウム",
  "マグネシウム",
  "アルミニウム",
  "ケイ素",
  "リン",
  "硫黄",
  "塩素",
  "アルゴン",
  "カリウム",
  "カルシウム",
  "スカンジウム",
  "チタン",
  "バナジウム",
  "クロム",
  "マンガン",
  "鉄",
  "コバルト",
  "ニッケル",
  "銅",
  "亜鉛",
  "ガリウム",
  "ゲルマニウム",
  "ヒ素",
  "セレン",
  "臭素",
  "クリプトン",
  "ルビジウム",
  "ストロンチウム",
  "イットリウム",
  "ジルコニウム",
  "ニオブ",
  "モリブデン",
  "テクネチウム",
  "ルテニウム",
  "ロジウム",
  "パラジウム",
  "銀",
  "カドミウム",
  "インジウム",
  "スズ",
  "アンチモン",
  "テルル",
  "ヨウ素",
  "キセノン",
  "セシウム",
  "バリウム",
  "ランタン",
  "セリウム",
  "プラセオジム",
  "ネオジム",
  "プロメチウム",
  "サマリウム",
  "ユウロピウム",
  "ガドリニウム",
  "テルビウム",
  "ジスプロシウム",
  "ホルミウム",
  "エルビウム",
  "ツリウム",
  "イッテルビウム",
  "ルテチウム",
  "ハフニウム",
  "タンタル",
  "タングステン",
  "レニウム",
  "オスミウム",
  "イリジウム",
  "白金",
  "金",
  "水銀",
  "タリウム",
  "鉛",
  "ビスマス",
  "ポロニウム",
  "アスタチン",
  "ラドン",
  "フランシウム",
  "ラジウム",
  "アクチニウム",
  "トリウム",
  "プロトアクチニウム",
  "ウラン",
  "ネプツニウム",
  "プルトニウム",
  "アメリシウム",
  "キュリウム",
  "バークリウム",
  "カリホルニウム",
  "アインスタイニウム",
  "フェルミウム",
  "メンデレビウム",
  "ノーベリウム",
  "ローレンシウム",
  "ラザフォージウム",
  "ドブニウム",
  "シーボーギウム",
  "ボーリウム",
  "ハッシウム",
  "マイトネリウム",
  "ダームスタチウム",
  "レントゲニウム",
  "コペルニシウム",
  "ニホニウム",
  "フレロビウム",
  "モスコビウム",
  "リバモリウム",
  "テネシン",
  "オガネソン"
]
